SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE*30)*(100-P.DISCOUNT_RATE)/100) AS "FEE"
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= "22-11-01"
    )
    ) AS H
ON C.CAR_ID = H.CAR_ID
INNER JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = "30일 이상") AS P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ("세단", "SUV")
AND ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
